config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'static_pages#home'
  get  "/admin" => 'static_pages#admin'
  resources :posts
  namespace :api do
    namespace :v1 do
      resources :posts
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    self.per_page = 5
end

# set per_page globally
WillPaginate.per_page = 5

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  skip_before_action :verify_authenticity_token

  # GET /posts
  # GET /posts.json
  def index
   @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.json { render :show, status: :created, location: @post }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.json { render :show, status: :ok, location: @post }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
   @posts = Post.paginate(:page => params[:page]).order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    def home
        @posts = Post.paginate(:page => params[:page]).order(created_at: :desc)
    end

    def admin
        @posts = Post.all.all.order(created_at: :desc)
    end


end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<!-- Panel Bottom #22 -->
<nav class="panel bottom">
        <div class="sections">
          <div class="center"><span class="nextSlide"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#arrow-down"></use></svg></span></div>
        </div>
      </nav>

app/views/layouts/_header.html.erb
<!-- Navigation -->
    <!-- Panel Top #02 -->
      <nav class="panel top forceMobileView">
        <div class="sections desktop">
          <div class="left"><%= link_to '<svg style="width:107px;height:31px"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#logomin"></use></svg>'.html_safe, root_path %></div>
          <div class="center">
            <ul class="menu">
                      <li><%= link_to "Share a story", new_post_path %></li>
                      <li><%= link_to "Read stories", posts_path %></li>
            </ul>
          </div>
           <div class="right"> <span class="button actionButton dropdownTrigger" data-dropdown-id="1"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#share"></use></svg></span> </div>
        </div>
        <div class="sections compact hidden">
          <div class="left"><%= link_to '<svg style="width:107px;height:31px"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#logomin"></use></svg>'.html_safe, root_path %></div>
          <div class="right">
            <span class="button actionButton dropdownTrigger" data-dropdown-id="1"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#share"></use></svg></span><span class="button actionButton sidebarTrigger" data-sidebar-id="1"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu"></use></svg></span>
          </div>
        </div>
      </nav>
      
      <!-- Sidebar -->
      <nav class="sidebar blue" data-sidebar-id="1">
        <div class="close"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#close"></use></svg></div>
        <div class="content">  
        <%= link_to '<svg style="width:107px;height:31px;color "><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#logomin"></use></svg>'.html_safe, root_path %>
        <ul class="mainMenu uppercase">
          
                <li><%= link_to "Share a story", new_post_path %></li>
                <li><%= link_to "Read stories", posts_path %></li>
          </ul>
        </div>
      </nav>
      
      <!-- Share Window -->
      <div class="dropdown share top right" data-dropdown-id="1" data-text="Check out this new initiative" data-url="http://www.goodfridayinitiative.com">
        <div class="title">Share</div>
        <ul>
          <li class="facebook"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#fb-like"></use></svg></li>
          <li class="twitter"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#twitter"></use></svg></li>
          <li class="googlePlus"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#googlePlus"></use></svg></li>
          <!-- <li class="pinterest"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#pinterest"></use></svg></li> -->
          <!-- li class="stumbleupon"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#stumbleupon"></use></svg></li>
          <li class="linkedin"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#linkedin"></use></svg></li -->
          <li class="mail" data-subject="Good Friday Initiative" data-body="Check out this new initiative by Red Bank Chapel.">share by email</li>
        </ul>
      </div>

app/views/posts/_adminfeed.html.erb
<nav class="side">
        <div class="navigation">
          <ul></ul>
        </div>
      </nav>
        <% @posts.each do |post| %>
        <!-- Slide 3 (#72) -->
    <section class="slide whiteSlide">
        <div class="content">
          <div class="container">
            <div class="wrap">
      
              <div class="fix-12-12 left">
                <div class="fix-9-12 toLeft">
                  <div class="ae-1 fromRight"><h2 class="hero">He led me to <%= post.title %></h2>
                  <p class="ae-5"><%= post.description %></p>
                  <%= link_to 'Edit', edit_post_path(post), class:"button gray" %> <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class:"button red" %>
                  <!-- <a href="#" class="button gray"> Edit </a><a href="#" class="button red">Delete</a></div> -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
        <% end %>

app/views/posts/_feed.html.erb
<nav class="side">
        <div class="navigation">
          <ul></ul>
        </div>
      </nav>
      <!-- <section><div><p id="notice"><%= notice %></div> -->
      </section>
     
        <% @posts.each do |post| %>
        <!-- Slide 3 (#72) -->
    <section class="slide whiteSlide">
        <div class="content">
          <div class="container">
            <div class="wrap">
      
              <div class="fix-12-12 left">
                <div class="fix-9-12 toLeft">
                  <div class="ae-1 fromRight"><h2 class="hero">He led me to <%= post.title %></h2></div>
                  <p class="ae-5"><%= post.description %></p>
                </div>
              </div>
      
            </div>
          </div>
        </div>
      </section>
        <% end %>
    
        <section class="slide whiteSlide">
            <div class="content">
              <div class="container">
                <div class="wrap">
                    <%= will_paginate @posts, class:"apple_pagination center", :page_links => false %>
                  </br>
                  <div class="fix-12-12 center">  
                          <%= link_to 'Share a story', new_post_path, class:"button green ae-2"%>
                  </div>      
                </div>
              </div>
            </div>
          </section>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :he_led_me_to %>
    <%= form.text_field :title, id: :post_title, placeholder: "Love my neighbor", required: "true" %>
  </div>

  <div class="field">
    <%= form.label :story %>
    <%= form.text_area :description, id: :post_description, placeholder: "....share the story.", required: "true" %>
  </div>
<div>
    <%= form.submit 'Share', class:"button green wide ae-10 cropBottom" %> </br>
</div>
<% end %>

app/views/posts/edit.html.erb
<section class="slide whiteSlide" name="form">
        <div class="content">
          <div class="container">
            <div class="wrap">
      
              <h1 class="ae-1">Editing Post</h1>
              <div class="ae-2"><p></p></div>
              <div class="fix-5-12 margin-top-6">
                <div class="pad shadow selected ae-3">

                <%= render 'form', post: @post %>

                <!-- <%= link_to 'Show', @post %> | -->
                <p><%= link_to 'Back', posts_path %></p>
                </div>
            </div>
            </div>
          </div>
        </div>
</section>

app/views/posts/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<!-- <div onLoad="pageScroll()"> -->
<%= render 'posts/feed'%>

app/views/posts/new.html.erb
<section class="slide whiteSlide" name="form">
        <div class="content">
          <div class="container">
            <div class="wrap">
      
              <h1 class="ae-1">Share your story</h1>
              <div class="ae-2"><p></p></div>
              <div class="fix-5-12 margin-top-6">
                <div class="pad shadow selected ae-3">
  
                    <%= render 'form', post: @post %></br>
                    
                    <!-- <p class="button pink"><%= link_to 'Back', posts_path %></p> -->
                </div>
            </div>
            </div>
          </div>
        </div>
</section>

app/views/posts/show.html.erb
    <section class="slide whiteSlide">
        <div class="content">
          <div class="container">
            <div class="wrap">
                <p id="notice"><%= notice %></p>
              <!-- <h1 class="ae-1">Post</h1> -->
               <p><strong>Title:</strong>
               <%= @post.title %></p>

                <p>
                  <strong>Description:</strong>
                  <%= @post.description %>
                </p>

<!-- <div><%= link_to 'Edit', edit_post_path(@post), class:"button gray" %></br> -->
<%= link_to 'Read Stories', posts_path, class:"button blue"%></div>
</div> </div>

app/views/static_pages/admin.html.erb
<% if admin_signed_in? %>
<%= link_to 'logout', destroy_admin_session_path, method: :delete %>
<%= render 'posts/adminfeed' %>
<% else %>
<%controller.redirect_to new_admin_session_path %>
<% end %>

app/views/static_pages/home.html.erb
<section class="slide whiteSlide" name ="top">
        <div class="content">
          <div class="container">
            <div class="wrap">
      
              <div class="fix-6-12">
                <svg height="150" class="wide ae-1 fromCenter">
                  <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#logo"></use>
                </svg>
              </div>
      
            </div>
          </div>
        </div>
 </section>
 <%= render 'posts/feed'%>